include gruvbox.conf

shell_integration disabled 

font_family MartianMono Nerd Font Mono 
font_size 12.0

cursor_shape block
cursor_shape_unfocused beam 
cursor_beam_thickness 1.5
cursor_blink_interval 0

scrollbar never
scrollbar_interactive no

sync_to_monitor no

enable_audio_bell no

remember_window_size no
remeber_window_position no
window_margin_width 10
confirm_os_window_close 0
